# 服务端口
server:
    port: 8009
spring:
  # 服务名称
  application:
    name: service-acl
  # mysql数据库连接
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/acldb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: duhonglei
  # redis连接
  redis:
    host: 192.168.229.129
    port: 6379
    database:  0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        # 最大阻塞等待时间（负数表示没限制）
        max-wait: -1
        max-idle: 5
        # 最小空闲
        min-idle: 0
  cloud:
    nacos:
      discovery:
        # nacos服务地址
        server-addr: 192.168.229.129:8848
  jackson:
    # 返回json的的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  # 配置 mapper xml文件的路径
  mapper-locations: classpath:mapper/*.xml
  configuration: 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
