# 端口号
server:
  port: 8222
spring:
  # 服务名称
  application:
    name: service-gateway
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.229.129:8848
    gateway:
      # 使用服务发现路由
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes[0]:
        id: service-acl
        # 设置路由的uri
        uri: lb://service-acl
        # 具体路径规则
        predicates: Path=/*/acl/**